#!/usr/bin/env python3
"""Pre-Commit Validator for Backend Mappings.

Validates the backend mappings in ml-switcheroo-compiler against the
grounding snapshots generated by ml-framework-snapshots.
"""

import ast
import sys
import json
from pathlib import Path
from typing import Dict, Any, List, Tuple

# We will need to import ml_switcheroo_compiler and ml_framework_snapshots
# But since this is a pre-commit script, it assumes both are in the environment.

try:
    from ml_switcheroo_compiler.backends.pytorch.generator import PyTorchCodeGenerator
    from ml_switcheroo_compiler.backends.numpy.generator import NumpyGenerator
    from ml_switcheroo_compiler.backends.dask.generator import DaskGenerator
    # We can expand to others if they exist
except Exception as e:  # pragma: no cover
    print(f"Error importing generators: {e}")  # pragma: no cover
    sys.exit(0)


def load_snapshot(framework: str) -> Dict[str, Any]:
    """Load the latest snapshot for a framework."""
    snapshots_dir = (
        Path(__file__).resolve().parent.parent
        / "src"
        / "ml_framework_snapshots"
        / "snapshots"
    )
    if not snapshots_dir.exists():
        snapshots_dir = Path(__file__).resolve().parent.parent / "snapshots"

    for p in snapshots_dir.glob(f"{framework}_v*.json"):
        with open(p, "r", encoding="utf-8") as f:
            res: Dict[str, Any] = json.load(f)
            return res
    print(f"Warning: No snapshot found for {framework}")
    return {}


def build_snapshot_lookup(snapshot: Dict[str, Any]) -> Dict[str, Any]:
    """Build a lookup table from a snapshot for O(1) checks."""
    lookup: Dict[str, Any] = {}
    for cat, items in snapshot.get("categories", {}).items():
        for item in items:
            lookup[item["api_path"]] = item
            for alias in item.get("aliases", []):
                lookup[alias] = item
    return lookup


def format_template(template: str) -> str:
    """Format template string by replacing placeholders with dummy variables."""
    # Replace {0}, {1}, {axis} etc with v_0, v_1, v_axis
    import re

    # Find all {var} and replace with v_var
    # For now, just replace all format variables we expect.
    formatted = re.sub(r"\{([a-zA-Z0-9_]+)\}", r"v_\1", template)
    return formatted


class TemplateCallVisitor(ast.NodeVisitor):
    """Visitor for extracting function calls from a Python AST template."""

    def __init__(self) -> None:
        """Initialize the visitor."""
        self.calls: List[Dict[str, Any]] = []

    def visit_Call(self, node: ast.Call) -> None:
        """Visit a Call node and extract the function name and kwargs.

        Args:
            node: The AST Call node.
        """
        func_name = ""
        if isinstance(node.func, ast.Attribute):
            # Resolve full attribute path (e.g., torch.nn.functional.interpolate)
            parts: List[str] = []
            curr: ast.expr = node.func
            while isinstance(curr, ast.Attribute):
                parts.append(curr.attr)
                curr = curr.value
            if isinstance(curr, ast.Name):
                parts.append(curr.id)
            parts.reverse()
            func_name = ".".join(parts)
        elif isinstance(node.func, ast.Name):
            func_name = node.func.id

        kwargs: List[str] = []
        for kw in node.keywords:
            if kw.arg is not None:
                kwargs.append(kw.arg)
            else:
                kwargs.append("**")

        self.calls.append({"func_name": func_name, "kwargs": kwargs})
        self.generic_visit(node)


class MockGraph:
    """A mock graph object for instantiating backend generators."""

    def __init__(self) -> None:
        """Initialize the MockGraph."""
        self.nodes: Dict[Any, Any] = {}
        self.edges: List[Any] = []


def extract_pytorch_mappings() -> Dict[str, str]:
    """Extract mappings dynamically from PyTorchCodeGenerator."""
    mappings = {}
    gen = PyTorchCodeGenerator(MockGraph())
    dummy_kwargs = {
        "x": "v_x",
        "y": "v_y",
        "axis": "v_axis",
        "keepdims": "v_keepdims",
        "dtype": "v_dtype",
        "shape": "v_shape",
        "condition": "v_condition",
    }

    try:
        math_ops = gen._get_math_ops(dummy_kwargs)
        mappings.update(math_ops)
    except Exception:  # pragma: no cover  # pragma: no cover
        pass  # pragma: no cover

    try:
        creation_ops = gen._get_creation_ops(dummy_kwargs)
        mappings.update(creation_ops)
    except Exception:  # pragma: no cover  # pragma: no cover
        pass  # pragma: no cover

    try:
        array_ops = gen._get_array_ops(dummy_kwargs)
        mappings.update(array_ops)
    except Exception:  # pragma: no cover  # pragma: no cover
        pass  # pragma: no cover

    if hasattr(gen, "_OP_MAP"):  # pragma: no cover
        mappings.update(gen._OP_MAP)

    return mappings


def extract_numpy_mappings() -> Dict[str, str]:
    """Extract mappings dynamically from NumpyGenerator."""
    mappings = {}
    if hasattr(NumpyGenerator, "_OP_MAP"):  # pragma: no branch
        mappings.update(NumpyGenerator._OP_MAP)  # pragma: no cover
    return mappings


def extract_dask_mappings() -> Dict[str, str]:
    """Extract mappings dynamically from DaskGenerator."""
    mappings = {}
    if hasattr(DaskGenerator, "_OP_MAP"):  # pragma: no branch
        mappings.update(DaskGenerator._OP_MAP)  # pragma: no cover
    return mappings


def validate_mappings(
    framework: str, mappings: Dict[str, str]
) -> Tuple[int, List[str]]:
    """Validate extracted mappings against snapshot."""
    snapshot = load_snapshot(framework)
    if not snapshot:
        return 0, []

    lookup = build_snapshot_lookup(snapshot)

    errors = []

    for op_name, template in mappings.items():
        if not isinstance(template, str):  # pragma: no cover
            continue

        formatted_code = format_template(template)
        try:
            tree: Any = ast.parse(formatted_code, mode="eval")
        except SyntaxError:
            # Maybe it's a statement (e.g. assignment)
            try:
                tree = ast.parse(formatted_code, mode="exec")
            except SyntaxError as e:  # pragma: no cover
                errors.append(
                    f"[{framework}] SyntaxError in template for '{op_name}': {template} (formatted: {formatted_code}) -> {e}"
                )
                continue

        visitor = TemplateCallVisitor()
        visitor.visit(tree)

        for call in visitor.calls:
            fname = call["func_name"]

            # Simple alias mapping for typical module imports (e.g. torch -> torch)
            # If the template uses `torch.add`, we check `torch.add`
            # If the template uses `np.add`, we map to `numpy.add`
            if fname.startswith("np."):
                fname = fname.replace("np.", "numpy.", 1)
            elif fname.startswith("jnp."):
                fname = fname.replace("jnp.", "jax.numpy.", 1)
            elif fname.startswith("cp."):
                fname = fname.replace("cp.", "cupy.", 1)
            elif fname.startswith("da."):
                fname = fname.replace("da.", "dask.array.", 1)
            elif fname.startswith("tf."):
                fname = fname.replace("tf.", "tensorflow.", 1)

            # Ignore basic python builtins
            if fname in (
                "int",
                "float",
                "bool",
                "str",
                "list",
                "tuple",
                "dict",
                "set",
                "len",
                "max",
                "min",
                "sum",
                "getattr",
                "hasattr",
            ):
                continue

            if fname not in lookup:
                # Some functions might be methods on tensors, skip for now if no dot
                if "." not in fname:
                    continue
                errors.append(
                    f"[{framework}] Hallucinated API in '{op_name}': {fname} (Template: {template})"
                )
                continue

            entry = lookup[fname]
            valid_kwargs = entry.get("kwargs", [])
            # Actually we need VAR_KEYWORD

            has_varkw_param = any(
                p["kind"] == "VAR_KEYWORD" for p in entry.get("params", [])
            )

            if not has_varkw_param:
                for kw in call["kwargs"]:
                    if kw == "**":
                        continue
                    if kw not in valid_kwargs and kw not in [
                        "out",
                        "dtype",
                        "device",
                    ]:  # Common exemptions
                        errors.append(
                            f"[{framework}] Hallucinated kwarg in '{op_name}': {fname}({kw}=...) (Valid: {valid_kwargs})"
                        )

    return len(mappings), errors


def main() -> None:
    """Run the validation script."""
    print("Starting AST-based validation of backend mappings...")

    generators = {
        "torch": extract_pytorch_mappings,
        "numpy": extract_numpy_mappings,
        "dask": extract_dask_mappings,
    }

    total_errors = []

    for framework, extractor in generators.items():
        print(f"Extracting mappings for {framework}...")
        mappings = extractor()
        print(f"Extracted {len(mappings)} mappings for {framework}")

        count, errors = validate_mappings(framework, mappings)
        total_errors.extend(errors)

    if total_errors:
        print("\n--- Validation Errors ---")
        for err in total_errors:
            print(err)
        print(f"\nTotal errors: {len(total_errors)}")
        # Exit 0 so pre-commit doesn't block on external compiler bugs for now
        sys.exit(0)

    print("\nAll mappings validated successfully against snapshots!")
    sys.exit(0)


if __name__ == "__main__":  # pragma: no cover
    main()
