name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Create required directories and set permissions
      run: |
        sudo mkdir -p /Users/samuel/repos
        sudo chown -R $(whoami) /Users

    - name: Checkout ml-switcheroo-ir
      uses: actions/checkout@v7
      with:
        repository: SamuelMarks/ml-switcheroo-ir
        path: ml-switcheroo-ir

    - name: Move ml-switcheroo-ir
      run: mv ml-switcheroo-ir /Users/samuel/repos/ml-switcheroo-ir

    - name: Install uv
      uses: astral-sh/setup-uv@v10.0.1
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv pip install --system pre-commit

    - name: Set up virtual environment
      run: |
        uv pip install --system -e ".[test,generate]" build pytest pytest-cov

    - name: Run pre-commit
      run: pre-commit run --all-files
